✨report 적중률 DB 업데이트 과정 제외 함수 구현체 작성 완료
sellpointSogang/Server pull request #29
Opened 2023-09-24 16:46 UTC by SoftCoffee1

<구현 내용>
report 인스턴스의 적중률 관련 변수 들어갈 숫자 계산하는 함수 구현.

<할 말>
RDS상에 올라가있는 report 인스턴스에 접근해서 실제 디비 내용 채우는 건 내일 해보려고 합니다..!

2023-09-25 03:01 UTC, go-the-extra-mile requested changes
수고하셨습니다. 코멘트 확인해주세요~
추가로, 같은 논리를 담은`calculate_hit_rate_of_report(report_instance)`를 만들어주시는게 맞으시죠?

2023-09-25 06:12 UTC, SoftCoffee1 commented on analysts/views.py
> -from .models import *
analysts/serializers.py 안을 확인해보면 Analyst 모델이 import 되어 있어요.
그래서 line5로 serializers를 import 해주면 line8이 에러가 나지는 않아요!
근데 보니까 가독성이 조금 떨어지는 것 같아서 앞으로 모델 추가할때는 line6를 적어줄게요.

2023-09-25 06:15 UTC, SoftCoffee1 commented on test_code/stockPrice.py
> +    else:
저 코드에는 차이가 없는 게 맞고, 가장 최신 리포트가 아닌 경우의 유효기간을 다음 리포트 공개날까지로 parameter 수정해야하긴 합니다!

그건 DB를 채워넣으면서 오늘 마무리하겠습니다~

2023-09-25 06:15 UTC, SoftCoffee1 commented on test_code/stockPrice.py
> +                    if days_hit == 0:
포매터 설정 얼른 하겠습니다 ㅎㅎ..

2023-09-25 06:18 UTC, SoftCoffee1 commented on test_code/stockPrice.py
> +                else:
말씀하신대로 맞추지 못한 것은 틀린것이라는 로직이 더 좋을 것 같긴하네요. 그렇게 수정해보겠습니다~

2023-09-25 15:48 UTC, SoftCoffee1 commented
<구현 내용>
1. fetch.py의 get_price_on_publish, get_stock_code 함수 완료
2. calculate_hit_rate_of_report 함수 장고 커맨드로 호출 할 수 있도록 구현 완료
         --> python manage.py scrape --calculate report
         
<할 일>
1. calculate_hit_rate_of_analyst 함수 장고 커맨드로 호출 할 수 있도록 구현하기

2023-09-25 16:39 UTC, SoftCoffee1 commented
<구현 내용>
1. calculate_hit_rate_of_analyst 함수: CLI 로 호출하여 DB 상의 계산되지 않은 모든 애널리스트의 적중률 계산하여 DB에 저장되도록 구현 완료
        --> python manage.py scrape --calculate analyst 로 실행

2023-09-26 07:38 UTC, go-the-extra-mile reviewed
수고하셨습니다! 코멘트 확인해주세요~

2023-09-26 07:38 UTC, go-the-extra-mile commented on reports/fetch.py
> +            days_to_first_miss_sum += report.days_to_first_miss
여기서도 `aggregate()`로 쿼리 수를 줄일 수 있을 것 같습니다. 
```python
from django.db.models import Sum

total = Report.objects.aggregate(
    total_days_hit=Sum('days_hit'),
    total_days_missed=Sum('days_missed'),
    total_days_to_first_hit=Sum('days_to_first_hit'),
    total_days_to_first_miss=Sum('days_to_first_miss')
)
```
이제 total은 total_days_hit, total_days_missed, ...를 키로 가지는 사전이 됩니다.

2023-09-26 08:14 UTC, SoftCoffee1 reviewed
코멘트 피니쉬를 안눌렀군요 ㅎㅎ..

2023-09-26 08:14 UTC, SoftCoffee1 commented on reports/fetch.py
> +        ]
성능 상 더 좋은것이라면 변경하겠습니다! 그런데 제가 보기에는 두 코드 모두 Writes.objects.filter(analyst=analyst)를 1번 호출하고, 제안해주신 코드에는 reports 쿼리셋을 얻어내는 과정에서 DB를 한번 더 건드리는 것으로 보이는데 어느 관점에서 더 적은 쿼리인지 여쭤보고 싶습니다!

2023-09-26 08:14 UTC, SoftCoffee1 commented on reports/fetch.py
> +            days_to_first_miss_sum += report.days_to_first_miss
혹시 dot method(ex. report.days_hit)를 쓰는 과정에서 DB에 쿼리문을 날리게 되나요? 그런게 맞다면 제안해주신 코드가 더 적은 쿼리 수인 것이 맞지만, 그것이 아니라면 제 코드에서는 쿼리문을 날리는 과정이 없는 것 같습니다.

2023-09-26 08:15 UTC, SoftCoffee1 commented on reports/management/commands/scrape.py
> +                help="List of stock names to scrape with spaces in between(ex. 삼성전자 카카오)",
수정하겠습니다!

2023-09-26 08:35 UTC, go-the-extra-mile commented on reports/fetch.py
> +        ]
뒤의 aggregate와 함께 생각하면 성능이 개선된다고 생각합니다! 
지금의 코드는 list comprehension 라인에서 write의 개수(=애널리스트가 쓴 리포트 수)만큼 쿼리가 발생합니다. 
그런데 이 코멘트의 수정사항과 aggregate 문을 사용하면 리포트 수가 변해도 쿼리 수가 변하지 않습니다.

2023-09-26 08:35 UTC, go-the-extra-mile commented on reports/fetch.py
> +            days_to_first_miss_sum += report.days_to_first_miss
아닙니다 list comprehension 과정에서 쿼리가 생깁니다.

2023-09-26 12:41 UTC, merged